### ISSUE TITLE
PSU

### ISSUE THREAD

**Issue by guestisp** [robotfish42/alkabot#2]
which PSU are you using and with stepper motors? (amps and torque)

**Comment by robotfishe** [comment]
The PSU I'm using is a generic 12V brick from RS Components - anything that can manage at least 2 amps should do it. The stepper motors were from an old 3D printer, not sure of the specs but based on the size I'd say they're probably around 25-30 Ncm. I'm giving them 800mA each but they could probably go lower. It's a pretty forgiving build in this regard, there's no significant force fighting the motors anywhere.

**Comment by guestisp** [comment]
thank you . do you have a wiring schema? i've only found a description in the install guide but a wiring schema would be useful or even some detailed pics (the general one doesn't show the inside)

why don't you suggest petg for dosing pumps? It has more strengtg than pla

**Comment by robotfishe** [comment]
I don't have a proper wiring diagram at the moment - I've only just started figuring out Fritzing a couple weeks ago. Maybe with the next version when I have time for that.

PETG is "stronger" than PLA in the sense of taking more force to actually _break_, but PLA is _stiffer_ which is what's important for pump accuracy. Something like carbon fibre-reinforced PETG would be the ideal material but is probably overkill considering how much it costs.

**Comment by guestisp** [comment]
even an hand made schema would be ok 😂

**Comment by guestisp** [comment]
@robotfishe i have some issue with the reagent dosing pump. even using a little big hose (i'm using a 1mm/2mm and not 0.8mm/1.9mm) there is a massive backflow that makes impossible to dose the reagent as it's not pick up from the container.

any idea? how many bearings are expected to be in contact with the tube, at any time? because i think there is just one

**Comment by robotfishe** [comment]
You might try reprinting the tube clamp or even using the 1.6mm version to increase the tightness of the grip on the tubing.
