### ISSUE TITLE
Which pH sensor ?

### ISSUE THREAD

**Issue by guestisp** [robotfish42/alkabot#3]
Which ph sensor (isolated) board are you using ? 
Do you have a link ?

**Comment by robotfishe** [comment]
Currently I'm using an Atlas Scientific consumer-grade pH probe which I ordered from Whitebox Labs: https://www.whiteboxes.ch/shop/consumer-grade-ph-probe/

I've found it marginally more reliable than the Grove probe I was previously using, but it's 2.5 times the price so you may or may not find that worth it.

**Comment by guestisp** [comment]
that's the probe but what about the sensor board and the optoisolator, if you are using one ?

**Comment by robotfishe** [comment]
I think the sensor board is still just the generic one that came with the Grove probe - https://coolcomponents.co.uk/products/grove-ph-sensor-kit-e-201c-blue

Don't consider this a recommendation, though, it's really just what I had on hand. As far as I know, a lot of these analogue pH boards are basically the same regardless of how they're branded, sometimes with different mounting layouts.

**Comment by guestisp** [comment]
don't you use any analog isolator between the board and the Nano ? Usually the ph has to be optoisolated to reduce the electrical noise.

**Comment by robotfishe** [comment]
Optoisolators don't work for analog signals, at least not the normal kind. You could add something like [this](https://www.dfrobot.com/product-1621.html) if you're concerned about signal noise but I haven't found it necessary and I don't think it's particularly common to add extra isolators between a pH sensor board and an arduino.

**Comment by guestisp** [comment]
well, Atlas suggest the use of an isolator when using their sensor
